import { Component, Input, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { ScoreData } from '../../shared/models/score-data.model';

@Component({
  selector: 'app-pdf-report',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (result) {
      <div class="w-0 h-0 overflow-hidden opacity-0 pointer-events-none absolute top-0 left-0">
        <div
          #pdfContent
          class="bg-white text-gray-900 flex flex-col"
          style="width: 800px; min-height: 1130px; padding: 40px; box-sizing: border-box;"
        >
          <div class="flex items-center justify-between border-b pb-6 mb-8">
            <div>
              <h1 class="text-3xl font-black text-[#007AFF] tracking-tight">Smile Intelligence</h1>
              <p class="text-gray-500 font-medium">Personalized Dental Analysis Report</p>
            </div>
            <div class="text-right">
              <p class="text-sm font-bold text-gray-900">{{ today }}</p>
              <p class="text-xs text-gray-500 mt-1">Generated by AI</p>
            </div>
          </div>
          <div class="flex gap-8 mb-10">
            <div class="flex-1">
              <div class="rounded-2xl overflow-hidden shadow-sm border border-gray-100 bg-gray-50 aspect-[3/4]">
                <img
                  [src]="imageSrc"
                  alt="Patient Scan"
                  class="w-full h-full object-cover"
                />
              </div>
            </div>
            <div class="flex-1 flex flex-col justify-center">
              <div class="flex items-center justify-center mb-8">
                <div class="relative w-48 h-48 flex items-center justify-center rounded-full border-[12px] border-[#007AFF]/20">
                  <div class="text-center z-10 bg-white rounded-full w-full h-full flex flex-col items-center justify-center shadow-sm border-[12px] border-white">
                    <span class="text-6xl font-black tracking-tighter text-gray-900">{{ result.smileScore }}</span>
                    <span class="text-xs font-bold text-gray-400 uppercase tracking-widest mt-1">Total Score</span>
                  </div>
                </div>
              </div>
              <div class="grid grid-cols-2 gap-4">
                <div class="bg-[#F2F2F7] p-4 rounded-xl">
                  <p class="text-xs font-bold text-gray-500 uppercase">Alignment</p>
                  <p class="text-2xl font-black text-[#007AFF]">{{ result.breakdown?.alignmentScore }}%</p>
                </div>
                <div class="bg-[#F2F2F7] p-4 rounded-xl">
                  <p class="text-xs font-bold text-gray-500 uppercase">Gum Health</p>
                  <p class="text-2xl font-black text-[#34C759]">{{ result.breakdown?.gumHealthScore }}%</p>
                </div>
                <div class="bg-[#F2F2F7] p-4 rounded-xl">
                  <p class="text-xs font-bold text-gray-500 uppercase">Whiteness</p>
                  <p class="text-2xl font-black text-[#FF9500]">{{ result.breakdown?.whitenessScore }}%</p>
                </div>
                <div class="bg-[#F2F2F7] p-4 rounded-xl">
                  <p class="text-xs font-bold text-gray-500 uppercase">Risk Level</p>
                  <p class="text-xl font-black mt-1" [class.text-red-500]="result.breakdown?.plaqueRiskLevel === 'High'" [class.text-green-500]="result.breakdown?.plaqueRiskLevel !== 'High'">
                    {{ result.breakdown?.plaqueRiskLevel }}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="mt-4">
            <h2 class="text-2xl font-bold text-gray-900 border-b pb-3 mb-6">Personalized Care Plan</h2>
            <div class="space-y-4">
              @for (action of result.carePlanActions; track $index) {
                <div class="flex gap-4 items-start p-4 rounded-xl border border-gray-100 bg-[#F2F2F7]/50">
                  <div class="w-8 h-8 rounded-full bg-white text-[#007AFF] font-bold flex items-center justify-center flex-shrink-0 shadow-sm border border-gray-100">
                    {{ $index + 1 }}
                  </div>
                  <div>
                    <div class="flex items-center gap-3 mb-1">
                      <h3 class="font-bold text-gray-900 text-lg">{{ action.title }}</h3>
                      <span
                        class="text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider"
                        [ngClass]="{
                          'bg-red-100 text-red-600': action.impact?.toLowerCase() === 'high',
                          'bg-orange-100 text-orange-600': action.impact?.toLowerCase() === 'medium',
                          'bg-blue-100 text-blue-600': action.impact?.toLowerCase() !== 'high' && action.impact?.toLowerCase() !== 'medium'
                        }"
                      >
                        {{ action.impact }} Impact
                      </span>
                    </div>
                    <p class="text-sm font-bold text-gray-500 uppercase tracking-widest mb-2">{{ action.category }}</p>
                    <p class="text-sm text-gray-700 font-medium leading-relaxed">{{ action.description }}</p>
                  </div>
                </div>
              }
            </div>
          </div>
          <div class="mt-auto pt-8 border-t border-gray-100 text-center">
            <p class="text-xs text-gray-400 font-medium">
              This report is generated by AI and is for informational purposes only. It does not replace professional dental advice.
            </p>
          </div>
        </div>
      </div>
    }
  `
})
export class PdfReportComponent {
  @ViewChild('pdfContent') contentRef!: ElementRef<HTMLDivElement>;
  @Input() result: ScoreData | null = null;
  @Input() imageB64 = '';
  today = new Date().toLocaleDateString();

  get imageSrc(): string {
    if (!this.imageB64) return '';
    return this.imageB64.startsWith('http') ? this.imageB64 : `data:image/jpeg;base64,${this.imageB64}`;
  }
}
